### ISSUE TITLE
[QUESTION] Better way of doing this assignment?

### ISSUE THREAD

**Issue by dhilipsiva** [amitkaps/pandas-workshop#1]
`imdb.groupby(["actor_1_name","actor_2_name"])["actor_1_name","actor_2_name"].count().sort(["actor_1_name","actor_2_name"])`

@amitkaps ?

**Comment by amitkaps** [comment]
@dhilipsiva This will not account for combinations where the actor 1 and actor 2 are same, but the order is different. One possible ways is this...

```
actor12 = imdb.pivot_table(index="actor_1_name", columns="actor_2_name", 
                   values="movie_title", aggfunc=lambda x: len(x.unique()), fill_value=0)

actor12.unstack().sort_values(ascending=False).head()

```
Have pushed this to the repo.
The next question is how do you extend this for actor_1, actor_2 and actor_3? :-)

**Comment by dhilipsiva** [comment]
@amitkaps Wow! Nice! This is a much elegant solution. I was trying to solve an other problem when you were teaching about using pivots - so it is a little grey. Sure thing. I will try to come up with a solution when I find time. Will close this Issue for now 😄
